# -*- coding: utf-8 -*-
"""Task4_DataStorytelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJCCOWxGT9vHrywvtDhP_iBEuFVoWflW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import ttest_ind

df = pd.read_csv("/content/StudentsPerformance.csv")

df.head()

df["overall_average"] = (
    df["math score"] +
    df["reading score"] +
    df["writing score"]
) / 3

gender_avg = df.groupby("gender")[
    "overall_average"
].mean()

print(gender_avg)

lunch_avg = df.groupby("lunch")[
    "overall_average"
].mean()

print(lunch_avg)

parent_avg = df.groupby(
    "parental level of education"
)["overall_average"].mean()

print(parent_avg)

gender_avg.plot(kind="bar")

plt.ylabel("Average Score")

plt.show()

lunch_avg.plot(kind="bar")

plt.ylabel("Average Score")

plt.show()

parent_avg.plot(kind="bar")

plt.xticks(rotation=45)

plt.show()

parent_avg.plot(kind="bar")

plt.xticks(rotation=45)

plt.show()

group1 = df[df['gender'] == 'female']['overall_average']
group2 = df[df['gender'] == 'male']['overall_average']

t_stat, p_value = ttest_ind(group1, group2)

print("P-value:", p_value)

p_value < 0.05

df.to_csv("task4_analysis.csv", index=False)